### ISSUE TITLE
Replace sketch

### ISSUE THREAD

**Issue by cob222** [Esri/arcgis-pro-sdk-community-samples#23] opened 2017-05-03 18:19 UTC
Replace sketch not working any more. The command is in the sketch dropdown but doesn't do anything. Tried it on two computers same thing. It used to work and I haven't changed anything with the system. I deleted, downloaded the zip and started over with the same result. What gives? Thanks ,cob

**Comment by Wolf-K** [comment] 2017-05-03 19:27
Appears to be a duplicate of #24

**Closed by Wolf-K** 2017-05-03 19:27 UTC
Labels: duplicate
